### ISSUE TITLE
Criar formulário de agendamento

### ISSUE THREAD

**Issue by quaresmateo** [SEDEPTI-BC/sad-front-end#3]
Este é o formulário que será preenchido pelo usuário para efetuar o agendamento

To do
-----

- [x] pegar equipamentos da API

- [x] enviar dados para a API
- [x] desativar do datepicker dias/horários de acordo com dias desativados (ver [API](https://github.com/SEDEPTI-BC/sad-back-end/issues/11))

- [x] limite mínimo e limite máximo ao selecionar horários do evento (closes #26)

- [x] substituir input timer por check list

- [x] validação de campos. (closes #14) Regras:
   - nome deve ser completo
   - limitar tamanho da descrição
   - título obrigatório
   - verificar formato de email
   - data obrigatório
   - horários obrigatórios
   - horários devem está dentro do horário disponível

**Comment by quaresmateo** [comment]
- [ ] Eviar dados para a API (depois de #40 )

- [ ] Limit mínimo e limite máximo ao selecionar horário do evento (closes #26)

- [ ] desativar dias/horários de acordo com dias desativados que será fornecido pela API
